spring.application.name=backend-springboot-vinylshop-controller
PSQL_DATABASENAME=VinylShop
PSQL_USERNAME=marjolijn-verspiek
PSQL_USERPASSWORD=password

#Database url, username en password
spring.datasource.url=jdbc:postgresql://localhost:5432/${PSQL_DATABASENAME}
spring.datasource.username=${PSQL_USERNAME}
spring.datasource.password=${PSQL_USERPASSWORD}

#Jpa instellingen
spring.jpa.show-sql=true

#Genereer database structuur
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create

# data.sql
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
